import type { MatrixLayerId, MatrixLayerConfig } from './multiDomainMatrixTypes';

export const MATRIX_LAYERS: MatrixLayerConfig[] = [
  {
    id: 'gym',
    label: '🏋️ Siłownia',
    shortLabel: 'Siłownia',
    icon: '🏋️',
    colorClass: 'bg-primary',
    badgeClass: 'text-primary bg-primary/10 border-primary/20',
    description: 'Trening siłowy z wolnymi ciężarami / maszynami',
  },
  {
    id: 'run',
    label: '🏃 Bieg',
    shortLabel: 'Bieg',
    icon: '🏃',
    colorClass: 'bg-warning',
    badgeClass: 'text-warning bg-warning/10 border-warning/20',
    description: 'Biegi zarejestrowane w Strava',
  },
  {
    id: 'protein',
    label: '🥩 Białko ≥140g',
    shortLabel: 'Białko',
    icon: '🥩',
    colorClass: 'bg-success',
    badgeClass: 'text-success bg-success/10 border-success/20',
    description: 'Podaż białka wspierająca anabolizm i sytość',
  },
  {
    id: 'carbs',
    label: '🍚 Węgle ≥200g',
    shortLabel: 'Węgle',
    icon: '🍚',
    colorClass: 'bg-warning/80',
    badgeClass: 'text-warning bg-warning/10 border-warning/20',
    description: 'Podaż węglowodanów dla resyntezy glikogenu',
  },
  {
    id: 'sleep',
    label: '🌙 Sen ≥80 / ≥7.5h',
    shortLabel: 'Sen',
    icon: '🌙',
    colorClass: 'bg-info',
    badgeClass: 'text-info bg-info/10 border-info/20',
    description: 'Jakość snu według pierścienia Oura',
  },
  {
    id: 'readiness',
    label: '💓 Readiness ≥80',
    shortLabel: 'Readiness',
    icon: '💓',
    colorClass: 'bg-primary/70',
    badgeClass: 'text-primary bg-primary/10 border-primary/20',
    description: 'Stan gotowości układu nerwowego i HRV',
  },
  {
    id: 'powerlist',
    label: '⚡ Power List ≥3',
    shortLabel: 'Power',
    icon: '⚡',
    colorClass: 'bg-info/80',
    badgeClass: 'text-info bg-info/10 border-info/20',
    description: 'Ukończenie co najmniej 3 zadań krytycznych dnia',
  },
  {
    id: 'incident',
    label: '🚫 Incydent (Lenie)',
    shortLabel: 'Incydent',
    icon: '🚫',
    colorClass: 'bg-danger',
    badgeClass: 'text-danger bg-danger/10 border-danger/20',
    description: 'Zarejestrowane załamanie dyscypliny / relapse',
  },
  {
    id: 'habits',
    label: '🧘 Nawyki ≥50%',
    shortLabel: 'Nawyki',
    icon: '🧘',
    colorClass: 'bg-accent',
    badgeClass: 'text-accent bg-accent/10 border-accent/20',
    description: 'Ukończona przynajmniej połowa aktywnych nawyków',
  },
];

export const DEFAULT_ACTIVE_LAYERS: MatrixLayerId[] = [
  'gym',
  'run',
  'protein',
  'carbs',
  'sleep',
  'powerlist',
  'incident',
];
