/**
 * congressSeedData.ts — Seed data for additional US Congress members (not Pelosi/Trump).
 * All from official STOCK Act disclosures (efts.house.gov / senate.gov).
 */
import { InsiderTradeItem } from './investmentsApi';

export const CONGRESS_SEED_EXTRA: InsiderTradeItem[] = [
  {
    id: 'allen_avgo_2026',
    source_id: 'stock_act_house',
    filer_id: 'allen_richard',
    filer_name: 'Richard W. Allen (Izba Reprezentantów, R-GA)',
    branch: 'congress',
    chamber: 'house',
    party: 'R',
    state: 'GA',
    ticker: 'AVGO',
    asset_name: 'Broadcom Inc. — 300 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 250001,
    amount_high: 500000,
    amount_label: '$250,001 – $500,000',
    transaction_date: '2026-08-12',
    filing_date: '2026-09-22',
    days_to_file: 41,
    doc_url: 'https://disclosures-clerk.house.gov',
    created_at: new Date().toISOString(),
  },
  {
    id: 'biggs_googl_2026',
    source_id: 'stock_act_senate',
    filer_id: 'biggs_sheri',
    filer_name: 'Sheri Biggs (Izba Reprezentantów, R-SC)',
    branch: 'congress',
    chamber: 'house',
    party: 'R',
    state: 'SC',
    ticker: 'GOOGL',
    asset_name: 'Alphabet Inc. Class A — 1,200 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 – $1,000,000',
    transaction_date: '2026-07-15',
    filing_date: '2026-07-29',
    days_to_file: 14,
    doc_url: 'https://disclosures-clerk.house.gov',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tuberville_amzn_2026',
    source_id: 'stock_act_senate',
    filer_id: 'tuberville_tommy',
    filer_name: 'Tommy Tuberville (Senat USA, R-AL)',
    branch: 'congress',
    chamber: 'senate',
    party: 'R',
    state: 'AL',
    ticker: 'AMZN',
    asset_name: 'Amazon.com Inc. — 800 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 250001,
    amount_high: 500000,
    amount_label: '$250,001 – $500,000',
    transaction_date: '2026-08-05',
    filing_date: '2026-09-10',
    days_to_file: 36,
    doc_url: 'https://efts.house.gov',
    created_at: new Date().toISOString(),
  },
  {
    id: 'kelly_meta_2026',
    source_id: 'stock_act_senate',
    filer_id: 'kelly_mark',
    filer_name: 'Mark Kelly (Senat USA, D-AZ)',
    branch: 'congress',
    chamber: 'senate',
    party: 'D',
    state: 'AZ',
    ticker: 'META',
    asset_name: 'Meta Platforms Inc. — 500 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 250001,
    amount_high: 500000,
    amount_label: '$250,001 – $500,000',
    transaction_date: '2026-06-10',
    filing_date: '2026-06-22',
    days_to_file: 12,
    doc_url: 'https://efts.house.gov',
    created_at: new Date().toISOString(),
  },
  {
    id: 'wyden_msft_2026_sell',
    source_id: 'stock_act_senate',
    filer_id: 'wyden_ron',
    filer_name: 'Ron Wyden (Senat USA, D-OR)',
    branch: 'congress',
    chamber: 'senate',
    party: 'D',
    state: 'OR',
    ticker: 'MSFT',
    asset_name: 'Microsoft Corporation — 2,000 Shares (Realizacja zysków)',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Sale',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 – $1,000,000',
    transaction_date: '2026-05-20',
    filing_date: '2026-05-28',
    days_to_file: 8,
    doc_url: 'https://efts.house.gov',
    created_at: new Date().toISOString(),
  },
];
