/**
 * gpwInsidersData.ts — Statyczne dane bazowe dla insiderów GPW (ESPI).
 */

import { GpwInsiderCluster, GpwInsiderEffectiveness, GpwInsiderKpis } from './gpwInsidersService';

export const DEFAULT_GPW_INSIDER_KPIS: GpwInsiderKpis = {
  purchases: 486,
  sales: 483,
  market90dPurchases: 616,
  market90dSales: 768,
  marketDeltaPoints: '+5.6 pkt',
  mostActiveTicker: 'BUMECH',
  mostActiveCount: 211,
  medianPerCompany: 3,
  tempo30d: 935,
  tempoAvg90d: 461,
  tempoGrowthPct: '+103%',
};

export const DEFAULT_GPW_CLUSTERS: GpwInsiderCluster[] = [
  {
    id: 'rob-1',
    ticker: 'ROB',
    companyName: 'ROBYG',
    buyersCount: 4,
    tradesCount: 6,
    totalValueFormatted: '—',
    dateRange: '29.06.2026 – 29.06.2026',
    insiders: ['Zbigniew Wojciech Okoński', 'Ewa Perkowska', 'Artur Ceglarz', 'Wojciech Gruza'],
  },
  {
    id: 'dvl-1',
    ticker: 'DVL',
    companyName: 'DEVELIA',
    buyersCount: 4,
    tradesCount: 4,
    totalValueFormatted: '—',
    dateRange: '31.07.2026 – 05.08.2026',
    insiders: ['Andrzej Oślizło', 'Paweł Ruszczak', 'Mariusz Poławski', 'Jacek Bagiński'],
  },
  {
    id: 'dvl-2',
    ticker: 'DVL',
    companyName: 'DEVELIA',
    buyersCount: 4,
    tradesCount: 8,
    totalValueFormatted: '—',
    dateRange: '15.07.2026 – 15.07.2026',
    insiders: ['Andrzej Oślizło', 'Paweł Ruszczak', 'Michał Hulbój', 'Leszek Stypułkowski'],
  },
  {
    id: 'zab-1',
    ticker: 'ZAB',
    companyName: 'ZABKA GROUP',
    buyersCount: 3,
    tradesCount: 3,
    totalValueFormatted: '—',
    dateRange: '13.08.2026 – 25.08.2026',
    insiders: ['Tomasz Suchański', 'Marta Wrochna-Łastowska', 'Jolanta Bańczerowska'],
  },
  {
    id: 'dad-1',
    ticker: 'DAD',
    companyName: 'DADELO',
    buyersCount: 3,
    tradesCount: 78,
    totalValueFormatted: '—',
    dateRange: '19.08.2026 – 15.09.2026',
    insiders: ['Ryszard Zawieruszyński', 'Jacek Zieziulewicz', 'Przemysław Kiełczewski'],
  },
  {
    id: 'snk-1',
    ticker: 'SNK',
    companyName: 'SANOK RUBBER COMPANY',
    buyersCount: 3,
    tradesCount: 3,
    totalValueFormatted: '—',
    dateRange: '04.09.2026 – 04.09.2026',
    insiders: ['Piotr Szamburski', 'Bartosz Sierpowski', 'Marta Rudnicka'],
  },
  {
    id: 'crj-1',
    ticker: 'CRJ',
    companyName: 'CREEPY JAR',
    buyersCount: 3,
    tradesCount: 3,
    totalValueFormatted: '—',
    dateRange: '11.08.2026 – 11.08.2026',
    insiders: ['Krzysztof Kwiatek', 'Tomasz Soból', 'Krzysztof Sałek'],
  },
  {
    id: 'ctx-1',
    ticker: 'CTX',
    companyName: 'CAPTOR THERAPEUTICS',
    buyersCount: 3,
    tradesCount: 3,
    totalValueFormatted: '—',
    dateRange: '10.08.2026 – 11.08.2026',
    insiders: ['Paweł Holstinghausen Holsten', 'Michał Walczak', 'Thomas Shepherd'],
  },
];

export const DEFAULT_GPW_EFFECTIVENESS: GpwInsiderEffectiveness[] = [
  {
    id: 'eff-1',
    personName: 'PRZEMYSŁAW MAZUREK',
    evalBuysCount: 20,
    median90s: 18.4,
    market90s: -6.25,
    diffPp: 24.65,
    ticker: 'NNG',
    lastTransactionDate: '15.02.2026',
  },
  {
    id: 'eff-2',
    personName: 'Kamila Stalmach',
    evalBuysCount: 7,
    median90s: 14.2,
    market90s: -2.71,
    diffPp: 16.91,
    ticker: 'XPL',
    lastTransactionDate: '18.11.2025',
  },
  {
    id: 'eff-3',
    personName: 'Adam Tychmanowicz',
    evalBuysCount: 12,
    median90s: 11.85,
    market90s: -4.17,
    diffPp: 16.02,
    ticker: 'YAN',
    lastTransactionDate: '06.07.2026',
  },
  {
    id: 'eff-4',
    personName: 'Multico Sp. z o.o.',
    isEntity: true,
    evalBuysCount: 3,
    median90s: 8.5,
    market90s: 0.24,
    diffPp: 8.26,
    ticker: 'MNC',
    lastTransactionDate: '29.07.2026',
  },
  {
    id: 'eff-5',
    personName: 'Ryszard Zawieruszyński',
    evalBuysCount: 10,
    median90s: 22.8,
    market90s: 1.66,
    diffPp: 21.14,
    ticker: 'DAD',
    lastTransactionDate: '09.09.2026',
  },
  {
    id: 'eff-6',
    personName: 'Blackwire Ventures sp. z o.o.',
    isEntity: true,
    evalBuysCount: 10,
    median90s: 15.3,
    market90s: -3.84,
    diffPp: 19.14,
    ticker: 'DMG',
    lastTransactionDate: '04.10.2024',
  },
  {
    id: 'eff-7',
    personName: 'Andrzej Sterczyński',
    evalBuysCount: 8,
    median90s: 9.4,
    market90s: 0.24,
    diffPp: 9.16,
    ticker: 'UNI',
    lastTransactionDate: '09.10.2025',
  },
  {
    id: 'eff-8',
    personName: 'Mielimonka Holding sp. z o.o.',
    isEntity: true,
    evalBuysCount: 19,
    median90s: 12.1,
    market90s: -6.56,
    diffPp: 18.66,
    ticker: 'DMG',
    lastTransactionDate: '19.09.2024',
  },
  {
    id: 'eff-9',
    personName: 'Dariusz Korecki',
    evalBuysCount: 7,
    median90s: 16.75,
    market90s: -4.0,
    diffPp: 20.75,
    ticker: 'SNT',
    lastTransactionDate: '20.02.2025',
  },
  {
    id: 'eff-10',
    personName: 'Radosław Kwaśnicki',
    evalBuysCount: 6,
    median90s: 13.4,
    market90s: 0.12,
    diffPp: 13.28,
    ticker: 'CRI',
    lastTransactionDate: '05.05.2025',
  },
  {
    id: 'eff-11',
    personName: 'Michał Nitka',
    evalBuysCount: 7,
    median90s: 19.6,
    market90s: 2.11,
    diffPp: 17.49,
    ticker: 'ASE',
    lastTransactionDate: '25.06.2025',
  },
  {
    id: 'eff-12',
    personName: 'Elephant Rock Fundacja Rodzinna',
    isEntity: true,
    evalBuysCount: 13,
    median90s: 7.9,
    market90s: -3.24,
    diffPp: 11.14,
    ticker: 'RBW',
    lastTransactionDate: '12.12.2024',
  },
  {
    id: 'eff-13',
    personName: 'Krzysztof Borusowski',
    evalBuysCount: 3,
    median90s: 14.5,
    market90s: -5.11,
    diffPp: 19.61,
    ticker: 'BST',
    lastTransactionDate: '09.09.2026',
  },
  {
    id: 'eff-14',
    personName: 'Marek Kucner',
    evalBuysCount: 3,
    median90s: 14.5,
    market90s: -5.11,
    diffPp: 19.61,
    ticker: 'BST',
    lastTransactionDate: '09.09.2026',
  },
  {
    id: 'eff-15',
    personName: 'Paweł Holstinghausen Holsten',
    evalBuysCount: 7,
    median90s: 10.25,
    market90s: -0.27,
    diffPp: 10.52,
    ticker: 'CTX',
    lastTransactionDate: '26.11.2025',
  },
];
