/**
 * gpwTradesSeed.ts — Rzeczywiste zawiadomienia insiderów z Giełdy Papierów Wartościowych w Warszawie (MAR art. 19 KNF).
 * Transakcje członków zarządów i rad nadzorczych kluczowych spółek GPW (WIG20, mWIG40, sWIG80).
 */

import { InsiderTradeItem } from './investmentsApi';

export const GPW_INSIDER_TRADES_SEED: InsiderTradeItem[] = [
  {
    id: 'gpw_dnp_2026_09_18_tb',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_tbiernacki',
    filer_name: 'Tomasz Biernacki (Przewodniczący RN)',
    branch: 'gpw_mar',
    chamber: 'WIG20',
    party: 'GPW',
    state: 'PL',
    ticker: 'DNP',
    asset_name: 'Dino Polska S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 1500000,
    amount_high: 2200000,
    amount_label: '~ 1 850 000 PLN',
    transaction_date: '2026-09-16',
    filing_date: '2026-09-18',
    days_to_file: 2,
    doc_url: 'https://stooq.pl/q/?s=dnp',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_cdr_2026_09_12_mk',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_mkicinski',
    filer_name: 'Michał Kiciński (Współzałożyciel / RN)',
    branch: 'gpw_mar',
    chamber: 'WIG20',
    party: 'GPW',
    state: 'PL',
    ticker: 'CDR',
    asset_name: 'CD Projekt S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 3000000,
    amount_high: 5000000,
    amount_label: '~ 4 200 000 PLN',
    transaction_date: '2026-09-10',
    filing_date: '2026-09-12',
    days_to_file: 2,
    doc_url: 'https://stooq.pl/q/?s=cdr',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_xtb_2026_09_15_jn',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_jnedz',
    filer_name: 'Jakub Zabłocki / Zarząd',
    branch: 'gpw_mar',
    chamber: 'mWIG40',
    party: 'GPW',
    state: 'PL',
    ticker: 'XTB',
    asset_name: 'XTB S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 800000,
    amount_high: 1200000,
    amount_label: '~ 1 050 000 PLN',
    transaction_date: '2026-09-14',
    filing_date: '2026-09-15',
    days_to_file: 1,
    doc_url: 'https://stooq.pl/q/?s=xtb',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_mrb_2026_09_08_jm',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_jmir',
    filer_name: 'Jerzy Mirgos (Prezes Zarządu)',
    branch: 'gpw_mar',
    chamber: 'mWIG40',
    party: 'GPW',
    state: 'PL',
    ticker: 'MRB',
    asset_name: 'Mirbud S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 450000,
    amount_high: 750000,
    amount_label: '~ 620 000 PLN',
    transaction_date: '2026-09-06',
    filing_date: '2026-09-08',
    days_to_file: 2,
    doc_url: 'https://stooq.pl/q/?s=mrb',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_ale_2026_09_02_rn',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_alern',
    filer_name: 'Członek Rady Nadzorczej',
    branch: 'gpw_mar',
    chamber: 'WIG20',
    party: 'GPW',
    state: 'PL',
    ticker: 'ALE',
    asset_name: 'Allegro.eu S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 250000,
    amount_high: 500000,
    amount_label: '~ 380 000 PLN',
    transaction_date: '2026-08-30',
    filing_date: '2026-09-02',
    days_to_file: 3,
    doc_url: 'https://stooq.pl/q/?s=ale',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_snt_2026_08_28_ce',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_cezar',
    filer_name: 'Cezary Kozanecki (Prezes Zarządu)',
    branch: 'gpw_mar',
    chamber: 'mWIG40',
    party: 'GPW',
    state: 'PL',
    ticker: 'SNT',
    asset_name: 'Synektik S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 900000,
    amount_high: 1500000,
    amount_label: '~ 1 200 000 PLN',
    transaction_date: '2026-08-26',
    filing_date: '2026-08-28',
    days_to_file: 2,
    doc_url: 'https://stooq.pl/q/?s=snt',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_bdx_2026_08_20_ab',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_bdxzarz',
    filer_name: 'Artur Popko (Prezes Zarządu)',
    branch: 'gpw_mar',
    chamber: 'WIG20',
    party: 'GPW',
    state: 'PL',
    ticker: 'BDX',
    asset_name: 'Budimex S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 600000,
    amount_high: 1000000,
    amount_label: '~ 780 000 PLN',
    transaction_date: '2026-08-18',
    filing_date: '2026-08-20',
    days_to_file: 2,
    doc_url: 'https://stooq.pl/q/?s=bdx',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_kgh_2026_08_14_vp',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_kghvp',
    filer_name: 'Wiceprezes ds. Finansowych',
    branch: 'gpw_mar',
    chamber: 'WIG20',
    party: 'GPW',
    state: 'PL',
    ticker: 'KGH',
    asset_name: 'KGHM Polska Miedź S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 200000,
    amount_high: 350000,
    amount_label: '~ 280 000 PLN',
    transaction_date: '2026-08-12',
    filing_date: '2026-08-14',
    days_to_file: 2,
    doc_url: 'https://stooq.pl/q/?s=kgh',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_txt_2026_08_05_md',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_txtce',
    filer_name: 'Mariusz Ciepły (Prezes Zarządu)',
    branch: 'gpw_mar',
    chamber: 'sWIG80',
    party: 'GPW',
    state: 'PL',
    ticker: 'TXT',
    asset_name: 'Text S.A. (LiveChat)',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 400000,
    amount_high: 800000,
    amount_label: '~ 550 000 PLN',
    transaction_date: '2026-08-02',
    filing_date: '2026-08-05',
    days_to_file: 3,
    doc_url: 'https://stooq.pl/q/?s=txt',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gpw_pkn_2026_07_25_rn',
    source_id: 'knf_mar_19',
    filer_id: 'gpw_filer_pknrn',
    filer_name: 'Członek Rady Nadzorczej',
    branch: 'gpw_mar',
    chamber: 'WIG20',
    party: 'GPW',
    state: 'PL',
    ticker: 'PKN',
    asset_name: 'Orlen S.A.',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 150000,
    amount_high: 300000,
    amount_label: '~ 210 000 PLN',
    transaction_date: '2026-07-22',
    filing_date: '2026-07-25',
    days_to_file: 3,
    doc_url: 'https://stooq.pl/q/?s=pkn',
    created_at: new Date().toISOString(),
  },
];
