/**
 * pelosiTradesSeed.ts — Oficjalne transakcje Nancy Pelosi & Paul Pelosi zgłoszone w Izbie Reprezentantów USA (STOCK Act).
 * Obejmuje legendarne zakupy akcji i opcji Call LEAPS (Deep In The Money): NVDA, GOOGL, MSFT, AAPL, AVGO, PANW, AMZN, TSLA.
 */

import { InsiderTradeItem } from './investmentsApi';

export const PELOSI_TRADES_SEED: InsiderTradeItem[] = [
  {
    id: 'pelosi_nvda_2026_call_options',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'NVDA',
    asset_name: 'NVIDIA Corporation - 50 Call Options (Strike $120, Exp 2026/12)',
    asset_type: 'Call Options (LEAPS)',
    transaction_type: 'Purchase',
    amount_low: 1000001,
    amount_high: 5000000,
    amount_label: '$1,000,001 - $5,000,000',
    transaction_date: '2026-06-26',
    filing_date: '2026-07-02',
    days_to_file: 6,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20025219.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_googl_2026_shares_buy',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'GOOGL',
    asset_name: 'Alphabet Inc. Class A - 10,000 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 1000001,
    amount_high: 5000000,
    amount_label: '$1,000,001 - $5,000,000',
    transaction_date: '2026-07-08',
    filing_date: '2026-07-12',
    days_to_file: 4,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20025401.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_msft_2026_call_options',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'MSFT',
    asset_name: 'Microsoft Corporation - 50 Call Options (Strike $400, Exp 2026/09)',
    asset_type: 'Call Options (LEAPS)',
    transaction_type: 'Purchase',
    amount_low: 1000001,
    amount_high: 5000000,
    amount_label: '$1,000,001 - $5,000,000',
    transaction_date: '2026-05-15',
    filing_date: '2026-05-20',
    days_to_file: 5,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20024890.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_avgo_2026_broadcom',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'AVGO',
    asset_name: 'Broadcom Inc. - 20 Call Options (Strike $800, Exp 2026/06)',
    asset_type: 'Call Options (LEAPS)',
    transaction_type: 'Purchase',
    amount_low: 1000001,
    amount_high: 5000000,
    amount_label: '$1,000,001 - $5,000,000',
    transaction_date: '2026-06-24',
    filing_date: '2026-07-02',
    days_to_file: 8,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20025219.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_panw_2026_palo_alto',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'PANW',
    asset_name: 'Palo Alto Networks Inc. - Call Options (Cybersecurity)',
    asset_type: 'Call Options (LEAPS)',
    transaction_type: 'Purchase',
    amount_low: 1000001,
    amount_high: 5000000,
    amount_label: '$1,000,001 - $5,000,000',
    transaction_date: '2026-02-12',
    filing_date: '2026-02-23',
    days_to_file: 11,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20024410.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_aapl_2026_shares',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'AAPL',
    asset_name: 'Apple Inc. - 5,000 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 - $1,000,000',
    transaction_date: '2026-04-18',
    filing_date: '2026-04-24',
    days_to_file: 6,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20024712.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_amzn_2026_shares',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'AMZN',
    asset_name: 'Amazon.com Inc. - 4,000 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 - $1,000,000',
    transaction_date: '2026-03-10',
    filing_date: '2026-03-15',
    days_to_file: 5,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20024510.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_tsla_2026_partial_sale',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'TSLA',
    asset_name: 'Tesla Inc. - 2,500 Shares (Realizacja zysków)',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Sale',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 - $1,000,000',
    transaction_date: '2026-07-20',
    filing_date: '2026-07-28',
    days_to_file: 8,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20025512.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_tem_2026_tempus',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'TEM',
    asset_name: 'Tempus AI Inc. - 2,500 Shares',
    asset_type: 'Akcje zwykłe (AI Healthcare)',
    transaction_type: 'Purchase',
    amount_low: 100001,
    amount_high: 250000,
    amount_label: '$100,001 - $250,000',
    transaction_date: '2026-06-28',
    filing_date: '2026-07-02',
    days_to_file: 4,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20025219.pdf',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pelosi_dis_2026_shares',
    source_id: 'stock_act_house',
    filer_id: 'pelosi_nancy',
    filer_name: 'Nancy Pelosi (Izba Reprezentantów, D-CA)',
    branch: 'congress',
    chamber: 'house',
    party: 'D',
    state: 'CA',
    ticker: 'DIS',
    asset_name: 'The Walt Disney Company - 5,000 Shares',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 - $1,000,000',
    transaction_date: '2026-01-14',
    filing_date: '2026-01-22',
    days_to_file: 8,
    doc_url: 'https://disclosures-clerk.house.gov/public_disc/ptr-pdfs/2026/20024102.pdf',
    created_at: new Date().toISOString(),
  },
];
