/**
 * trumpTradesSeed.ts — Oficjalne ujawnienia majątkowe Donalda Trumpa (OGE / FEC Form 278e).
 * Obejmuje udziały w DJT (Trump Media), amerykańskie obligacje skarbowe (T-Bills) oraz fundusze ETF.
 */

import { InsiderTradeItem } from './investmentsApi';

export const TRUMP_TRADES_SEED: InsiderTradeItem[] = [
  {
    id: 'trump_djt_2026_shares_holding',
    source_id: 'oge_form_278e',
    filer_id: 'trump_donald',
    filer_name: 'Donald J. Trump (Prezydent / Biały Dom)',
    branch: 'executive',
    chamber: 'White House',
    party: 'R',
    state: 'FL',
    ticker: 'DJT',
    asset_name: 'Trump Media & Technology Group Corp. (Truth Social)',
    asset_type: 'Akcje założycielskie (114.75M akcji)',
    transaction_type: 'Purchase',
    amount_low: 50000000,
    amount_high: 100000000,
    amount_label: '> $50,000,000',
    transaction_date: '2026-03-26',
    filing_date: '2026-04-10',
    days_to_file: 15,
    doc_url: 'https://www.sec.gov/edgar/browse/?CIK=0001849635',
    created_at: new Date().toISOString(),
  },
  {
    id: 'trump_tbills_2026_portfolio',
    source_id: 'oge_form_278e',
    filer_id: 'trump_donald',
    filer_name: 'Donald J. Trump (Prezydent / Biały Dom)',
    branch: 'executive',
    chamber: 'White House',
    party: 'R',
    state: 'FL',
    ticker: 'US-TBILL',
    asset_name: 'US Treasury Bills (Bony i obligacje skarbowe USA 3M-1Y)',
    asset_type: 'Obligacje rządowe',
    transaction_type: 'Purchase',
    amount_low: 25000000,
    amount_high: 50000000,
    amount_label: '$25,000,000 - $50,000,000',
    transaction_date: '2026-05-10',
    filing_date: '2026-06-01',
    days_to_file: 22,
    doc_url: 'https://www.oge.gov/web/oge.nsf/Officials',
    created_at: new Date().toISOString(),
  },
  {
    id: 'trump_spy_2026_sp500_etf',
    source_id: 'oge_form_278e',
    filer_id: 'trump_donald',
    filer_name: 'Donald J. Trump (Prezydent / Biały Dom)',
    branch: 'executive',
    chamber: 'White House',
    party: 'R',
    state: 'FL',
    ticker: 'SPY',
    asset_name: 'SPDR S&P 500 ETF Trust',
    asset_type: 'Fundusz ETF',
    transaction_type: 'Purchase',
    amount_low: 1000001,
    amount_high: 5000000,
    amount_label: '$1,000,001 - $5,000,000',
    transaction_date: '2026-02-15',
    filing_date: '2026-03-01',
    days_to_file: 14,
    doc_url: 'https://www.oge.gov/web/oge.nsf/Officials',
    created_at: new Date().toISOString(),
  },
  {
    id: 'trump_gld_2026_gold_shares',
    source_id: 'oge_form_278e',
    filer_id: 'trump_donald',
    filer_name: 'Donald J. Trump (Prezydent / Biały Dom)',
    branch: 'executive',
    chamber: 'White House',
    party: 'R',
    state: 'FL',
    ticker: 'GLD',
    asset_name: 'SPDR Gold Trust (Złoto fizyczne)',
    asset_type: 'Fundusz ETF (Kruszce)',
    transaction_type: 'Purchase',
    amount_low: 500001,
    amount_high: 1000000,
    amount_label: '$500,001 - $1,000,000',
    transaction_date: '2026-04-05',
    filing_date: '2026-04-20',
    days_to_file: 15,
    doc_url: 'https://www.oge.gov/web/oge.nsf/Officials',
    created_at: new Date().toISOString(),
  },
  {
    id: 'trump_lmt_2026_defense',
    source_id: 'oge_form_278e',
    filer_id: 'trump_donald',
    filer_name: 'Donald J. Trump (Prezydent / Biały Dom)',
    branch: 'executive',
    chamber: 'White House',
    party: 'R',
    state: 'FL',
    ticker: 'LMT',
    asset_name: 'Lockheed Martin Corporation (Obronność / F-35)',
    asset_type: 'Akcje zwykłe',
    transaction_type: 'Purchase',
    amount_low: 250001,
    amount_high: 500000,
    amount_label: '$250,001 - $500,000',
    transaction_date: '2026-01-20',
    filing_date: '2026-02-10',
    days_to_file: 21,
    doc_url: 'https://www.oge.gov/web/oge.nsf/Officials',
    created_at: new Date().toISOString(),
  },
];
